### ISSUE TITLE
Feature: User can record a mood

### ISSUE THREAD

**Issue by brian-luong** [brian-luong/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can record a mood

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can record a mood by clicking on the add icon 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/64977584/178391246-5e5cfed6-5232-4dab-9687-557067c8b0ea.png)
![image](https://user-images.githubusercontent.com/64977584/178391282-0cf157d9-8f56-41b8-9517-59dece03dce8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to postgressql
- [ ] Update `data.sql` to postgressql
- [ ] add some moods to database
- [ ] add a user

### ☁️ Server

- [ ] Sent post request to server whenever user adds mood
- [ ] Get res object
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Add event listener
- [ ] display new mood by date
- [ ] set default user to user

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
